version: '3'

services:

  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: f00b@r!
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/init_todomvc.sql
